### ISSUE TITLE
About Unsupervised Clustering Under VAE？

### ISSUE THREAD

**Issue by LynnHo** [ericjang/gumbel-softmax#6]
@ericjang Thanks for the good code! I wonder whether we could use gumbel-softmax for clustering under VAE framework (e.g. for Mnist, 392->..->10->..->392, and "10" represents the relaxed categorical distribution). I have tried, but got bad results. Do you have any idea?

**Comment by akihironitta** [comment]
I guess that feature representations learnt by squashing input, e.g. images, into only 10 dimensional categorical variable using encoder-decoder framework will be very sensitive to initial weights of NN because no label information is available in unsupervised learning tasks like clustering.
